### ISSUE TITLE
Level changes twice

### ISSUE THREAD

**Issue by jeena** [logsol/chuck.js#144] opened 2015-04-25 07:55 UTC
Stop people from playing after round end, this might lead to kills after the round is done and thus this would send another endRound and beginRound.

**Comment by logsol** [comment] 2016-08-28 20:36
there is now an endRound method in the channel gamecontroller. after it has been called, it shouldnt be possible to change the stats (kills)

**Comment by logsol** [comment] 2016-08-28 20:43
duplicate of #71

**Closed by logsol** 2016-08-28 20:43 UTC
Labels: bug, ready
