### ISSUE TITLE
After end game don't update stats

### ISSUE THREAD

**Issue by jeena** [logsol/chuck.js#71] opened 2014-05-29 20:26 UTC

**Comment by logsol** [comment] 2015-01-11 19:14
i feel like this should be blocked by #95. @jeena how do you feel about postponing this till after alpha release?

**Comment by jeena** [comment] 2015-01-12 19:26
Yeah it is not a big deal.

**Comment by logsol** [comment] 2015-01-12 23:49
:+1:

**Comment by logsol** [comment] 2015-03-03 15:21
we could use the pointerLockManager.isLocked mechanism for this, which prevents playing with the keyboard when the pointerLock is not active

**Comment by jeena** [comment] 2015-04-25 08:16
Will probably be fixed by #144

**Comment by logsol** [comment] 2016-08-28 20:42
there is now an endRound method in the channel gamecontroller. after it has been called, it shouldnt be possible to change the stats (kills)

**Comment by logsol** [comment] 2016-08-28 20:43
#144 was a duplicate of this

**Closed** 2016-10-01 14:52 UTC
Labels: blocked, bug, in progress
